modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/davidjjung/wilderflowers/issues"
license = "MIT License"

[[mods]]
modId = "wilderflowers"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "wilderflowers:hopeful_wildflowers"
configBackground = "minecraft:textures/block/dirt.png"
authors = "Kobber, cassiancc"
credits = "ProbablyEkho, DavigJ"
displayURL = "https://modrinth.com/project/wilder-flowers"
displayName = "Wilder Flowers"
description = '''
    Adds various wildflowers to world generation, as well as flower garlands.
    '''

[[dependencies.wilderflowers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wilderflowers]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"